### ISSUE TITLE
support 64 bit int using https://github.com/truecluster/bit64

### ISSUE THREAD

**Issue by mrchypark** [rgonomic/rgo#16]
### Background
rgo has limitation with 64-bit integers because R don't have 64-bit integers. 

### Proposal
https://github.com/truecluster/bit64 package support 64-bit integers in R.

**Comment by kortschak** [comment]
Unfortunately because of R's approach to providing a stable API for interacting with internals (they don't) I have had to remove the machinery that would have made this possible.

**Comment by mrchypark** [comment]
@kortschak Thank you for answer. I understand. close issue.
